language: python
python:
  - "2.7"
# command to install dependencies
install: "cd src-py && pip install -r requirements/base.txt  -r requirements/test.txt"
# command to run tests
script: "./pytest.sh"

