version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dcl-testpoint-image
    command: /code/src/docker-gunicorn.sh
    container_name: dcl-testpoint
    env_file: dcl-testpoint.env
    volumes:
      - ./src:/code/src
    ports:
      - "127.0.0.1:7777:8080"
